.TH BOTAN\-CONFIG\-1.10 1 2011\-08\-25 1.10.0 "Botan Configuration Query program"

.SH NAME
botan\-config\-1.10 \- Botan Configuration Query program

.SH SYNOPSIS
\fBbotan-config\-1.10\fR [\fB\-\-prefix[=DIR]\fR] [\fB\-\-version\fR] [\fB\-\-libs\fR] [\fB\-\-cflags\fR]

.SH DESCRIPTION
.PP
\fBbase\-config\fR
is used to access the configuration information of Botan.

.SH HOMEPAGE
More information about Botan Project can be found at <\fIhttp://botan.randombit.net/\fR>.

.SH AUTHOR
Botan was written by Jack Lloyd <lloyd@randombit.net>.
.PP
This manual page was written by Daniel Baumann <daniel@debian.org>, for the Debian project (but may be used by others).
